# Local Development - Only PostgreSQL and Redis

networks:
  ragit-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:

services:
  # Database
  postgres:
    image: postgres:15
    container_name: ragit-postgres
    environment:
      POSTGRES_DB: ragit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ragit-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: ragit-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - ragit-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
